### ISSUE TITLE
Crash selecting modue from browser [Win 10, Rack 2.1.2]

### ISSUE THREAD

**Issue by SteveRussell33** [patheros/JPLab#1]
Built using commit https://github.com/patheros/JPLab/commit/b75233adeffb0d462d1dce4fd15dee314f23a929
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff861a12ee3 in NoteWidget::draw (this=0x24e96488fd0, args=...) at src/widgets.hpp:345
345    NoteExtra extraValu = static_cast<NoteExtra>(knob->module->paramQuantities[knob->paramId + 1]->getValue());
(gdb) bt
#0  0x00007ff861a12ee3 in NoteWidget::draw (this=0x24e96488fd0, args=...) at src/widgets.hpp:345
#1  0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e9637b650, child=0x24e96488fd0, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#2  0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e9637b650, args=...) at src/widget/Widget.cpp:280
#3  0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e95cd3ce0, child=0x24e9637b650, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#4  0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=this@entry=0x24e95cd3ce0, args=...) at src/widget/Widget.cpp:280
#5  0x00007ff86a0b790a in rack::app::ModuleWidget::draw (this=0x24e95cd3ce0, args=...) at src/app/ModuleWidget.cpp:213
#6  0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e962ec470, child=0x24e95cd3ce0, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#7  0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=this@entry=0x24e962ec470, args=...) at src/widget/Widget.cpp:280
#8  0x00007ff86a0efc43 in rack::widget::FramebufferWidget::drawFramebuffer (this=0x24e962ec470) at src/widget/FramebufferWidget.cpp:293
#9  0x00007ff86a0f0739 in rack::widget::FramebufferWidget::render (this=0x24e962ec470, scale=..., offsetF=..., clipBox=...) at src/widget/FramebufferWidget.cpp:247
#10 0x00007ff86a0f0db2 in rack::widget::FramebufferWidget::draw (this=0x24e962ec470, args=...) at src/widget/FramebufferWidget.cpp:130
#11 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e962ec3f0, child=0x24e962ec470, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#12 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e962ec3f0, args=...) at src/widget/Widget.cpp:280
#13 0x00007ff86a0f286d in rack::widget::ZoomWidget::draw (this=0x24e962ec3f0, args=...) at src/widget/ZoomWidget.cpp:54
#14 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e963ef010, child=0x24e962ec3f0, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#15 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e963ef010, args=...) at src/widget/Widget.cpp:280
#16 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e963eef60, child=0x24e963ef010, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#17 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e963eef60, args=...) at src/widget/Widget.cpp:280
#18 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e962ec510, child=0x24e963eef60, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#19 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e962ec510, args=...) at src/widget/Widget.cpp:280
#20 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e96307450, child=0x24e962ec510, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#21 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e96307450, args=...) at src/widget/Widget.cpp:280
#22 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e962efee0, child=0x24e96307450, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#23 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e962efee0, args=...) at src/widget/Widget.cpp:280
#24 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e96302b70, child=0x24e962efee0, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#25 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=this@entry=0x24e96302b70, args=...) at src/widget/Widget.cpp:280
#26 0x00007ff86a0eb54f in rack::ui::ScrollWidget::draw (this=0x24e96302b70, args=...) at src/ui/ScrollWidget.cpp:68
#27 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e962fc7d0, child=0x24e96302b70, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#28 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e962fc7d0, args=...) at src/widget/Widget.cpp:280
#29 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e96256430, child=0x24e962fc7d0, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#30 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e96256430, args=...) at src/widget/Widget.cpp:280
#31 0x00007ff86a0f24c8 in rack::widget::Widget::drawChild (this=this@entry=0x24e95d42880, child=0x24e96256430, args=..., layer=layer@entry=0)
    at src/widget/Widget.cpp:311
#32 0x00007ff86a0f25e2 in rack::widget::Widget::draw (this=0x24e95d42880, args=...) at src/widget/Widget.cpp:280
#33 0x00007ff86a0f6872 in rack::window::Window::step (this=this@entry=0x24e95ccb9f0) at src/window/Window.cpp:504
#34 0x00007ff86a0f6998 in rack::window::Window::run (this=0x24e95ccb9f0) at src/window/Window.cpp:409
#35 0x00007ff774dc163b in main (argc=<optimized out>, argv=<optimized out>) at adapters/standalone.cpp:240
```

**Comment by SteveRussell33** [comment]
OK all good with e42cadd4dd073ff7be6c5d7ea399b3f6131e531b
